### ISSUE TITLE
"Save" does not work anymore

### ISSUE THREAD

**Issue by greenlaw110** [freewind/rythmfiddle#16]
Login as admin, clicking on "Save" button, there is no response. Check the chrome console, found the following error:

```
Error: Argument 'fn' is not a function, got Object
    at assertArg (http://rythmfiddle.gelinsoft.com/templates/lib/angular/angular.js:1005:11)
    at assertArgFn (http://rythmfiddle.gelinsoft.com/templates/lib/angular/angular.js:1015:3)
    at annotate (http://rythmfiddle.gelinsoft.com/templates/lib/angular/angular.js:2336:5)
    at Object.invoke (http://rythmfiddle.gelinsoft.com/templates/lib/angular/angular.js:2819:21)
    at http://rythmfiddle.gelinsoft.com/public/libs/bootstrap-ui/0.2.0/ui-bootstrap-tpls-0.2.0.js:765:80
    at Object.forEach (http://rythmfiddle.gelinsoft.com/templates/lib/angular/angular.js:140:20)
    at Dialog._loadResolves (http://rythmfiddle.gelinsoft.com/public/libs/bootstrap-ui/0.2.0/ui-bootstrap-tpls-0.2.0.js:763:15)
    at Dialog.open (http://rythmfiddle.gelinsoft.com/public/libs/bootstrap-ui/0.2.0/ui-bootstrap-tpls-0.2.0.js:645:12)
    at Object.save (http://rythmfiddle.gelinsoft.com/templates/js/controllers.js:186:11)
    at http://rythmfiddle.gelinsoft.com/templates/lib/angular/angular.js:6298:19 
```

**Comment by freewind** [comment]
Because I used a new version of "ui-bootstrap", whose dialog api has changed.
